### ISSUE TITLE
run-integration-test.sh is not working as intended

### ISSUE THREAD

**Issue by MCapitani** [rlite/rlite#80]
As in the title, when running the script after a clean installation, I see

```
./tests/run-integration-tests.sh: 33: [: Illegal number:
```
on a ubuntu 16.04 LTS with sh pointing to dash.

Shellcheck reports: `SC2039: In POSIX sh, EUID is undefined.` which would explain the problem

Other shellcheck warnings:

`SC2045: Iterating over ls output is fragile. Use globs.`
`SC2039: In POSIX sh, echo flags are undefined.`
`SC2166: Prefer [ p ] && [ q ] as [ p -a q ] is not well defined.`

and other minor warnings on quoting, which should not be a problem.

Most (but not all) of these warnings are no longer reported by shellcheck under bash (as opposed to sh), and the script works with no issues.

**Comment by vmaffione** [comment]
Fixed.
