### ISSUE TITLE
rinaperf: Display more statistics in ping mode

### ISSUE THREAD

**Issue by edugrasa** [rlite/rlite#82]
It would be great if rinaperf displayed more statistics in 'ping mode' when it ends the test (such as average, stdev, min, max rtt), or someone Ctrl-Cs it. Thanks :)

**Comment by vmaffione** [comment]
This feature has been implemented.
The output of `rinaperf` in ping mode should be now undistinguishable from the output of the popular "ping" command.
Moreover, adding the `-C` option will also dump over 100 latency percentiles, which are useful to plot CDF.
