### ISSUE TITLE
Connecting two remote applications of RINA with the help of rlite 

### ISSUE THREAD

**Issue by samsneelam1981** [rlite/rlite#90]
Can you please help me in connecting two nodes over different LANs (Remote applications which are not running over same LAN) using shim DIF concepts. 
Thank you

**Comment by vmaffione** [comment]
If you control the router node that connects the two LANs, you can setup RINA also on the router node, and configure a normal-over-shim-eth scenario (with two shim-eth DIFs, one per LAN).
If you don't control the router node, at least you should have IP connectivity between your two nodes. In this case you can setup a normal-over-shim-udp4 to tunnel RINA traffic between your nodes, which is the same setup described in the shim-udp4 tutorial.

Which case are you in?

**Comment by samsneelam1981** [comment]
![image](https://user-images.githubusercontent.com/48311499/55605992-b67e0800-5794-11e9-9c90-c27074b4fe90.png)
![proposed config file](https://user-images.githubusercontent.com/48311499/55606006-c1389d00-5794-11e9-94c0-5267f6017292.png)

This is my case. I would like to connect two systems like this. Please tell me the requirements and config procedure. Thank you for your response.

**Comment by vmaffione** [comment]
Can you reach the host on the left from the host on the right? Once you achieve this, all you need
to do is to do the udp4 tutorial between the two hosts.

I guess those routers are home DSL routers? In that case you should configure them for UDP port forwarding. Can you try to configure something like this:
https://www.wikihow.com/Open-Your-Port-80-Behind-a-Firewall
https://www.noip.com/support/knowledgebase/general-port-forwarding-guide/
on your home routers?

You can check for reachability using netcat (e.g. openbsd netcat):
First, you need to configure the router on the left to forward port 7000, and the router on the right
to forward port 8000. Then
On the host on the left, listen on port 7000:
````
    (left) $ nc -u -l 7000
````
On the host on the right, connect to port 7000, using 8000 as a source port
````
    (right) $ nc -u -p 8000 ${PUBLIC_IP_OF_LEFT_ROUTER} 7000
````
and then try to type some text and check that the text is transferred between the two netcat processes.

**Comment by samsneelam1981** [comment]
I am sorry to disturb you.. But the thing is my left side is connected to internet through a private network.  Right side is connected to a home broadband connection. May I know the modified configuration process. Thank you
